import fnmatch
import glob
import json
import logging
import os
import re
import shutil
import tempfile

import borgmatic.actions.restore
import borgmatic.config.paths

logger = logging.getLogger(__name__)

IS_A_HOOK = False


def make_data_source_dump_path(borgmatic_runtime_directory, data_source_hook_name):
    '''
    Given a borgmatic runtime directory and a data source hook name, construct a data source dump
    path.
    '''
    return os.path.join(borgmatic_runtime_directory, data_source_hook_name)


def make_data_source_dump_filename(
    dump_path, name, hostname=None, port=None, container=None, label=None
):
    '''
    Based on the given dump directory path, data source name, hostname, and port, return a filename
    to use for the data source dump. The hostname defaults to localhost.

    Raise ValueError if the data source name is invalid.
    '''
    if os.path.sep in name:
        raise ValueError(f'Invalid data source name {name}')

    if container:
        hostname = container
    elif not hostname:
        hostname = 'localhost'

    identifier = label if label else hostname + ('' if port is None else f':{port}')

    return os.path.join(dump_path, identifier, name)


def write_data_source_dumps_metadata(borgmatic_runtime_directory, hook_name, dumps_metadata):
    '''
    Given the borgmatic runtime directory, a data source hook name, and a sequence of
    borgmatic.actions.restore.Dump instances of dump metadata, write a metadata file describing all
    of those dumps. This metadata is being dumped so that it's available upon restore, e.g. to
    support the user selecting which data source(s) should be restored.

    Raise ValueError if writing to the file results in an operating system error.
    '''
    dumps_metadata_path = os.path.join(borgmatic_runtime_directory, hook_name, 'dumps.json')

    try:
        with open(dumps_metadata_path, 'w', encoding='utf-8') as metadata_file:
            json.dump(
                {
                    'dumps': [dump._asdict() for dump in dumps_metadata],
                },
                metadata_file,
                sort_keys=True,
            )
    except OSError as error:
        raise ValueError(f'Error writing to dumps metadata at {dumps_metadata_path}: {error}')


def parse_data_source_dumps_metadata(dumps_json, dumps_metadata_path):
    '''
    Given a dumps metadata JSON string as extracted from an archive and its path within the archive,
    parse it into a tuple of borgmatic.actions.restore.Dump instances and return them.

    Raise ValueError if parsing the JSON results in a JSON decode error or the data does not have
    the expected keys.
    '''
    try:
        return tuple(
            borgmatic.actions.restore.Dump(**dump) for dump in json.loads(dumps_json)['dumps']
        )
    except (json.JSONDecodeError, TypeError, KeyError) as error:
        raise ValueError(
            f'Cannot read archive data source dumps metadata at {dumps_metadata_path} due to invalid JSON: {error}',
        )


def create_parent_directory_for_dump(dump_path):
    '''
    Create a directory to contain the given dump path.
    '''
    os.makedirs(os.path.dirname(dump_path), mode=0o700, exist_ok=True)


def create_named_pipe_for_dump(dump_path):
    '''
    Create a named pipe at the given dump path.
    '''
    create_parent_directory_for_dump(dump_path)
    os.mkfifo(dump_path, mode=0o600)


def remove_data_source_dumps(dump_path, data_source_type_name, dry_run):
    '''
    Remove all data source dumps in the given dump directory path (including the directory itself).
    Also remove any dumps that look like they're leftover from a previous borgmatic run. If this is
    a dry run, then don't actually remove anything.
    '''
    dry_run_label = ' (dry run; not actually removing anything)' if dry_run else ''

    logger.debug(f'Removing {data_source_type_name} data source dumps{dry_run_label}')

    dump_paths_glob = borgmatic.config.paths.replace_temporary_subdirectory_with_glob(
        os.path.normpath(dump_path),
    )

    for path in glob.glob(dump_paths_glob):
        if not dry_run:
            logger.debug(f'Removing {path}')
            shutil.rmtree(path, ignore_errors=True)


END_OF_STRING_PATTTERN = re.compile(r'\\z', flags=re.IGNORECASE)


def convert_glob_patterns_to_borg_pattern(patterns):
    '''
    Convert a sequence of shell glob patterns like "/etc/*", "/tmp/*" to the corresponding Borg
    regular expression archive pattern as a single string like "re:etc/.*|tmp/.*".
    '''
    # This deserves some explanation. Here's what this code is doing for each shell glob pattern:
    #
    #  * Strip off the leading slash, since Borg doesn't store leading slashes in archives.
    #  * Use fnmatch.translate() to convert the pattern to a Borg pattern.
    #  * Remove the "\z" or \"Z" end-of-string special character generated by fnmatch.translate(),
    #    because Borg doesn't like it. Replace it with a "$" end-of-string special character
    #    instead. And yes, this is using a regular expression to modify a regular expression.
    #  * Do the above for each of:
    #    * The plain pattern. This supports the use case of a standard database where its name is a
    #      filename in the path. Example: borgmatic/foo_databases/hostname/test
    #    * The pattern with "/*" tacked onto the end of it. This supports the use case of a
    #      directory-format database where its name is a directory name in the path. Example:
    #      borgmatic/foo_databases/hostname/test/toc.dat
    #
    # Join the resulting transformed patterns together with "|" and return them as a string.
    return 're:' + '|'.join(
        re.sub(END_OF_STRING_PATTTERN, '$', fnmatch.translate(stripped))
        + '|'
        + re.sub(END_OF_STRING_PATTTERN, '$', fnmatch.translate(stripped + '/*'))
        for pattern in patterns
        for stripped in (pattern.lstrip('/'),)
    )


def strip_path_prefix_from_extracted_dump_destination(
    extract_path,
    hook_name,
    borgmatic_runtime_directory,
):
    '''
    Directory-format dump files get extracted into a temporary directory containing a path prefix
    that depends how the files were stored in the archive. So, given the path where the dump was
    extracted, the data source hook name, and the borgmatic runtime directory, move the dump files
    such that the restore doesn't have to deal with that varying path prefix.

    For instance, if the dump was extracted to:

      /run/user/0/borgmatic/tmp1234/borgmatic/postgresql_databases/test/...

    or:

      /run/user/0/borgmatic/tmp1234/root/.borgmatic/postgresql_databases/test/...

    then this function moves it to:

      /run/user/0/borgmatic/postgresql_databases/test/...
    '''
    for subdirectory_path, _, _ in os.walk(extract_path):
        hook_directory = os.path.basename(subdirectory_path)

        if hook_directory != hook_name:
            continue

        destination_path = os.path.join(borgmatic_runtime_directory, hook_directory)
        shutil.rmtree(destination_path, ignore_errors=True)
        shutil.move(subdirectory_path, destination_path)

        break


def extract_dump(
    repository,
    config,
    local_borg_version,
    global_arguments,
    local_path,
    remote_path,
    archive_name,
    hook_name,
    data_source,
    borgmatic_runtime_directory,
    dump_patterns,
):
    '''
    Given a repository dict, a configuration dict, the local Borg version, global arguments as an
    argparse.Namespace instance, the local Borg path, the remote Borg path, the archive name to
    extract from, the data source hook name, a data source dict, the borgmatic runtime directory,
    and the dump patterns to match against in the archive, extract the corresponding dump—either
    streaming via an extract process or, for directory format, written into the runtime directory.

    Return the extract process (or None for directory format).
    '''
    destination_path = (
        tempfile.mkdtemp(dir=borgmatic_runtime_directory)
        if data_source.get('format') == 'directory'
        else None
    )

    try:
        # Kick off a single data source extract. If using a directory format, extract to a temporary
        # directory. Otherwise extract the single dump file to stdout.
        extract_process = borgmatic.borg.extract.extract_archive(
            dry_run=global_arguments.dry_run,
            repository=repository['path'],
            archive=archive_name,
            paths=[
                borgmatic.hooks.data_source.dump.convert_glob_patterns_to_borg_pattern(
                    dump_patterns,
                ),
            ],
            config=config,
            local_borg_version=local_borg_version,
            global_arguments=global_arguments,
            local_path=local_path,
            remote_path=remote_path,
            destination_path=destination_path,
            # A directory format dump isn't a single file, and therefore can't extract
            # to stdout. In this case, the extract_process return value is None.
            extract_to_stdout=bool(data_source.get('format') != 'directory'),
        )

        if destination_path and not global_arguments.dry_run:
            strip_path_prefix_from_extracted_dump_destination(
                destination_path,
                hook_name,
                borgmatic_runtime_directory,
            )
    finally:
        if destination_path and not global_arguments.dry_run:
            shutil.rmtree(destination_path, ignore_errors=True)

    return extract_process
