---
kind: pipeline
name: python-3-8-alpine-3-13

services:
  - name: postgresql
    image: docker.io/postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
  - name: postgresql2
    image: docker.io/postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: test2
      POSTGRES_DB: test
      POSTGRES_USER: postgres2
    commands:
      - postgres -p 5433
  - name: mysql
    image: docker.io/mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
  - name: mysql2
    image: docker.io/mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: test2
      MYSQL_DATABASE: test
    commands:
      - mysqld --port=3307
  - name: mongodb
    image: docker.io/mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
  - name: mongodb2
    image: docker.io/mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root2
      MONGO_INITDB_ROOT_PASSWORD: test2
    commands:
      - mongod --port=27018

clone:
  skip_verify: true

steps:
- name: build
  image: docker.io/alpine:3.13
  environment:
    TEST_CONTAINER: true
  pull: always
  commands:
    - scripts/run-full-tests
---
kind: pipeline
name: documentation
type: exec

platform:
  os: linux
  arch: amd64

clone:
  skip_verify: true

steps:
- name: build
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    IMAGE_NAME: projects.torsion.org/borgmatic-collective/borgmatic:docs
  commands:
    - podman login --username "$USERNAME" --password "$PASSWORD" projects.torsion.org
    - podman build --tag "$IMAGE_NAME" --file docs/Dockerfile --storage-opt "overlay.mount_program=/usr/bin/fuse-overlayfs" .
    - podman push "$IMAGE_NAME"

trigger:
  repo:
    - borgmatic-collective/borgmatic
  branch:
    - main
  event:
    - push
