kind: pipeline
name: python-3-8-alpine-3-13

services:
  - name: postgresql
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
  - name: mysql
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
  - name: mongodb
    image: mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

clone:
  skip_verify: true

steps:
- name: build
  image: alpine:3.13
  pull: always
  commands:
    - scripts/run-full-tests
---
kind: pipeline
name: documentation

clone:
  skip_verify: true

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: projects.torsion.org
    repo: projects.torsion.org/borgmatic-collective/borgmatic
    tags: docs
    dockerfile: docs/Dockerfile

trigger:
  repo:
    - borgmatic-collective/borgmatic
  branch:
    - master
  event:
    - push
