#!/usr/bin/env bash

set -e

python_version=$(python --version)

if [[ "$python_version" =~ "Python 3.5." ]]; then
    echo "Skipping black due to lack of support for $python_version."
elif [[ "$python_version" =~ "Python 3.4." ]]; then
    echo "Skipping black due to lack of support for $python_version."
else
    black --skip-string-normalization --line-length 100 --check .
fi
