#!/bin/sh

# This script is for running all tests, including end-to-end tests, on a developer machine. It sets
# up database containers to run tests against, runs the tests, and then tears down the containers.
#
# Run this script from the root directory of the borgmatic source.
#
# For more information, see:
# https://torsion.org/borgmatic/docs/how-to/develop-on-borgmatic/

set -e

docker-compose --file tests/end-to-end/docker-compose.yaml up --force-recreate \
    --renew-anon-volumes --abort-on-container-exit
