#!/bin/sh

# This script installs test dependencies and runs all tests, including end-to-end tests. It
# is designed to run inside a test container, and presumes that other test infrastructure like
# databases are already running. Therefore, on a developer machine, you should not run this script
# directly. Instead, run scripts/run-full-dev-tests
#
# For more information, see:
# https://torsion.org/borgmatic/docs/how-to/develop-on-borgmatic/

set -e

python -m pip install --upgrade pip==20.2.4
pip install tox==3.20.1
export COVERAGE_FILE=/tmp/.coverage
apk add --no-cache borgbackup postgresql-client mariadb-client py3-typed-ast
tox --workdir /tmp/.tox
tox --workdir /tmp/.tox -e end-to-end
