#!/bin/sh

# This script is for running end-to-end tests on a developer machine. It sets up database containers
# to run tests against, runs the tests, and then tears down the containers.
#
# Run this script from the root directory of the borgmatic source.
#
# For more information, see:
# https://torsion.org/borgmatic/docs/how-to/develop-on-borgmatic/

set -e

USER_PODMAN_SOCKET_PATH=/run/user/$UID/podman/podman.sock

if [ -e "$USER_PODMAN_SOCKET_PATH" ]; then
    export DOCKER_HOST="unix://$USER_PODMAN_SOCKET_PATH"
fi

docker-compose --file tests/end-to-end/docker-compose.yaml --progress quiet up --force-recreate \
    --renew-anon-volumes --detach
docker-compose --file tests/end-to-end/docker-compose.yaml --progress quiet attach tests
docker-compose --file tests/end-to-end/docker-compose.yaml --progress quiet down
